copyright: Copyright © 2023 Just Article
extra:
  generator: false
  social:
  - icon: material/email
    link: mailto:benjamin0901@gmail.com
  - icon: material/web
    link: https://portaly.cc/kuimingchen
  - icon: simple/line
    link: https://line.me/ti/p/9hF6WBmdck
markdown_extensions:
- attr_list
- md_in_html
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg ''
    emoji_index: !!python/name:materialx.emoji.twemoji ''
nav:
- Home: index.md
- Articles:
  - Anthropic 融資 4.5 億美元用於構建下一代 AI 助手: 20230524111901.md
  - Google Product Studio 驚艷登場：AI 讓商家輕鬆創建產品圖像: 20230525231901.md
  - The surface of the sun is close to 6000 degrees, and it has heated the Earth, so why is space at absolute zero?: 2023053906480.md
  - 最狂！跑贏非洲人的日本公務員: 20230601113201.md
  - LeBron James Scores 38 Points, Reaches Career Total of 38,390 in Recent Game: 20230818160420328237.md
  - '"Kyle Anderson: China''s First Naturalized Basketball Player from the NBA"': 20230818160437166199.md
  - Celtics' Miraculous Comeback Ties NBA Eastern Conference Finals: 20230818160459469560.md
  - '"Jaylen Brown signs record-breaking $952 million contract extension with Celtics"': 20230818160520303848.md
  - Kerr's first postseason loss to a Western Conference team could spark Warriors' rebuild: 20230818160539825453.md
  - '"Gender Pay Equality in Sports: Achievable on the Eve of Women''s World Cup in New Zealand?"': 20230818160606776235.md
  - NBA Renames MVP Award as Michael Jordan Trophy, Honoring Basketball Legend: 20230818160641775980.md
  - Jeremy Lin Joins PLG Kaohsiung Steel in Taiwan, Supports "Great Southern Plan" for Taiwanese Basketball: 20230818160655531980.md
  - 'Article: Ja Morant''s Injury Forces Early Exit in Lakers vs. Grizzlies Playoff Match': 20230818161058997757.md
  - Carmelo Anthony Announces Retirement from NBA in Emotional Twitter Video: 20230818161143840136.md
  - '"Bronny James and Shareef O''Neal: Living in Fathers'' Shadows, Battling Heart Issues"': 20230818161214201286.md
  - 'From NBA Star to Successful Venture Capitalist: The Transformative Journey of Baron Davis': 20230818161319964304.md
  - '"LeBron James, 38, Makes NBA History with 28 Points Average"': 20230818161414015006.md
  - Exciting Surprises at This Year's Slam Dunk Contest: 20230818161450242309.md
  - Luka Doncic Makes NBA History with 250+ Points, 50+ Rebounds, and 50+ Assists in First 5 Games: 20230818161534369236.md
  - 'Scoring King: Simplifying the Art of Decorative Enhancements': 20230818161552441251.md
  - '2022 Recap: Warriors'' NBA Win, BTS Solo Career Announcement': 20230818161644962415.md
  - '"2023 NBA Draft held at Barclays Center in New York"': 20230818161719008992.md
  - '2022 Popular Keywords Review: Taiwan Star''s Disconnect and NAC Cough Medicine Rumor Go Viral': 20230818161747650077.md
  - 'Dwight Howard: A Potential Spiritual Master Beyond Basketball': 20230818161822094269.md
  - Trinity Rodman Shines in World Cup, Carving Her Own Path: 20230818161854297422.md
  - '"Denver Nuggets Win Game 5 of NBA Finals Against Miami Heat"': 20230818161913978791.md
  - '"San Antonio Spurs Secure Number One Victory in NBA"': 20230818161958798966.md
  - 'Title: Rockets'' Rebuilding Path: Balancing Stability and Aggressiveness': 20230818162014127352.md
  - Bai Yaocheng's Transformative Two-Year Journey: 20230818162045852903.md
  - 'Survival: The Diligent Genius Alasa''s Unwavering Efforts': 20230818162231474220.md
  - '"James Harden''s Evolving Role: From Championship Foundation to a Different Symbol"': 20230818162324025902.md
  - Chinese Men's Basketball Team Struggles with Persistent Point Guard Problem: 20230821093456883037.md
  - Problems to Watch in Recent Sun's Trading of Bol Bol for Cam Payne: 20230821093538507157.md
  - UC Irvine Coach Defeats Chinese Blue Team in Jones Cup Tournament: 20230821093601114518.md
  - Chinese White Team Wins in Fourth Quarter, Places Sixth in Jones Cup: 20230821093615206276.md
  - Monkey Team vs. Six Laws of the Great Sage Lin Bingsheng: 20230821093632422500.md
  - 'Gabe Norwood: A Veteran''s Journey in the 2023 Jones Cup': 20230821093649125950.md
  - 'Educational Significance of 2023 Jones Cup: Russell Turner''s Coaching Philosophy': 20230821093720344365.md
  - 'Steve Kerr''s First Playoff Loss to Western Conference Team: Lakers Defeat Golden State Warriors'' Head Coach': 20230821093745794049.md
  - '"Bronny James and Shareef O''Neal: Living in the Shadow of their Famous Fathers and Dealing with Heart Problems"': 20230821093807150898.md
  - '"NBA Spurs Win First Overall Pick, Expected to Draft French Prospect Victor Wembanyama"': 20230821093849809968.md
  - '"From Loss to Fatherhood: William Artino''s Journey in the 2023 Jones Cup"': 20230822132222958377.md
  - 'Temporary Stagnation in Free Agent Market Storm: Join Bulls Fans Discussion Group or Visit AhUtopian Sports Talk': 20230822132252100297.md
  - '"NBA Player Skal Labissiere Signs Partially Guaranteed One-Year Contract with Sacramento Kings, Reports Shams Charania"': 20230822132330120684.md
  - 'HBO''s "Winning Time: The Rise of the Lakers Dynasty" Season 2 premieres, based on Jeff Pearlman''s "Showtime" series': 20230822132338288746.md
  - Ateneo's Dominant Performance Secures Jones Cup Runner-Up for Team Chinese Blue: 20230822132413313774.md
  - 'Spurs'' First Overall Pick: Admiral David Robinson': 20230822132428056261.md
  - '"Steve Kerr''s Golden State Warriors Suffer First Playoff Loss to the Los Angeles Lakers"': 20230822132459881258.md
  - '"SBL2023 Rookie Draft Sets Record with 11 Players Selected"': 20230822132526274485.md
  - 'Wenell Carter Jr: BullsH1T202324 - Heart Over Head': 20230822132537220326.md
  - 'Top Keywords in June 2022: Warriors'' NBA Championship Win, BTS Announces Solo Careers': 20230823100629136207.md
  - '"Peak Essays: The Versatile Swiss Army Knife, Austin Reaves, Shines for US Team and Lakers"': 20230823100658101202.md
  - 'Bruce Brown: Timberwolves, not Lakers, posed toughest challenge in NBA series': 20230823100748742203.md
  - Thunder cut Tyty Washington Jr: 20230823100801392340.md
  - '"Bulls Fan Discussion Group: Temporary Stagnation in Free Agent Market"': 20230823100808159096.md
  - Kyle Anderson Becomes China's First Naturalized Basketball Player: 20230823100838970781.md
  - '"Japan Takes Early Lead Against France in World Cup Warm-up Game, Rudy Gobert Discusses Facing Fast Shooters"': 20230823100930504208.md
  - NBA Applauds Banchero's Learning Attitude, Compares Him to Knowledge-Hungry Sponge: 20230823100952191204.md
  - Michael Jordan's cameo in "Ultraman" as a baseball player: 20230823101009162125.md
  - Japan and France's World Cup warm-up match happened today.: 20230825055535158205.md
  - 'Title: Ja Morant Suffers Hand Injury, Forced to Exit Game Early': 20230825055559707431.md
  - '"Wang Zhiqun Takes Over as T1 League Secretary-General, Expected to Enhance League''s Benefits with His Experience"': 20230825055642459996.md
  - PLG legislator criticizes Taishin Bank for poaching Lin Ping-sheng from Attack Lions, seeks resolution: 20230825055704454753.md
  - Chinese Blue Team Dominates UAE, Scoring Over 100 Points in Jones Cup: 20230825055724136190.md
  - 'The Suns'' Recent Transactions: Bol Bol Trade and Cam Payne Deal for Second-Round Picks': 20230825055735655880.md
  - 'Stephen Curry vs. Magic Johnson: Who is the Greatest Point Guard?': 20230825055806700044.md
  - '"NBA Praises Banchero''s Learning Attitude, Compares Him to an Ever-Curious Sponge"': 20230825055819268330.md
  - '"2024 Hall of Fame Inductees Announced: Who Will Receive the Highest Honor?"': 20230825055829693716.md
  - 'SBL2023 Rookie Draft: Su Geer, First Pick; Jiang Haowen, Second; Guo Zhenfu, Third': 20230825055853358807.md
  - '"NBA Players Frequently Teased Off Court: Rondo, Paul, Wall, and Walker Among Favorites"': 20230826082918407973.md
  - Utah Jazz's New Season Expectations Face Real Test This Year: 20230826082935079707.md
  - China Blue and China White Teams Excel in 42nd William Jones Cup: 20230826082956194058.md
  - Chinese White Team's Fourth Quarter Victory Secures Sixth Place in Jones Cup Tournament: 20230826083033560975.md
  - '2023 FIBA World Cup Men''s Basketball Warm-up: Lithuania vs Latvia, World No.': 20230826083052198316.md
  - 2023 FIBA World Cup Warm-up Game Features Lithuanian "Death or Glory" Jersey: 20230826083131740518.md
  - 'NBA Star Kyrie Irving''s Unfulfilled Wish: Representing Australia in International Games': 20230826083206990057.md
  - 'Group B Pre-match Analysis: China, Serbia, South Sudan, and Puerto Rico in the 2023 Basketball World Cup': 20230826083217309231.md
  - 'Remembering January 26, 2020: A Tearful Recollection of Kobe Bryant': 20230826083316677717.md
  - '"T1 Alliance Taishin Warriors Unveils Team Name and Logo, Lin Bing-sheng and Sun Si-yao Added to Roster"': 20230826083418483941.md
  - '"Analyzing ''Peak Essays'': Evaluating USA Team and Austin Reaves of the Lakers"': 20230827120133155013.md
  - '"Admiral David Robinson: The Savior of the San Antonio Spurs"': 20230827120255132381.md
  - '"Jaden Ivey Shines as a Skilled Ball Handler: A Journey from the East to the Sunset"': 20230827120330102455.md
  - ? Olympic Qualifiers Nurkic and Musa Complain Again About the Inability of the
      Bosnian Basketball Federation to Provide Basic Needs
    : 20230827120358853380.md
  - 'The Struggles of Bronny James and Shareef O''Neal: Living in Their Fathers'' Shadows and Battling Heart Issues': 20230827120436764144.md
  - Chinese White Team Finishes Sixth in Jones Cup with Fourth Quarter Win: 20230827120508399351.md
  - 'Derrick White: The Unsung Hero of the Boston Celtics in 2022-23 Season': 20230827120529707436.md
  - '"Terance Mann''s changing perspective on LeBron vs Kobe rivalry"': 20230827120655152268.md
  - San Antonio Spurs' Interest in Austin Reaves' Contract Fades as Los Angeles Lakers Show Willingness to Match: 20230827120702890029.md
  - SBL2023新秀選秀：蘇格爾、江浩文、郭振福成為首輪選秀: 20230828091812089775.md
  - A'ja Wilson Ties WNBA Single-Game Scoring Record with 53-Point Performance: 20230828091831524251.md
  - '"President of Bahamas Basketball Association Hopes to Recruit Klay Thompson for Next Olympic Qualifiers"': 20230828091846596028.md
  - Kyle Anderson switches jersey number to 1 for World Cup; Zeng Fanbo sidelined from final roster due to injury: 20230828091858333204.md
  - '"Bulls'' Wenell Carter Jr. remains on people''s minds after BullsH1T202324"': 20230828091914647587.md
  - 'Russell Turner''s Coaching Philosophy: The Educational Significance of the 2023 Jones Cup Goes Beyond Basketball': 20230828092013667277.md
  - '"Unemployed NBA Players: Free Agency Updates"': 20230828092046613536.md
  - DeAndre Hunter's Development and the Atlanta Hawks' Dissatisfaction by 2023: 20230828092118388505.md
  - Contract dispute of former T1 League star Lin Bing-sheng gains attention: 20230828092616518097.md
  - Luka Doncic Makes NBA History with 250 Points, 50 Rebounds, and 50 Assists in 5 Games: 20230828092639420694.md
site_name: Just Article
site_url: https://ramens.io/
theme:
  custom_dir: overrides
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  name: material
  palette:
  - accent: orange
    media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference
  - accent: orange
    media: (prefers-color-scheme)
    primary: teal
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - accent: orange
    media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
